import { useState } from "react";
import { api } from '../../utils/api'
import { useRouter } from "next/router";
import Head from "next/head";


const Login = () => {
    const { mutate: login } = api.auth.login.useMutation();
    const router = useRouter();
    // const {data} = api.example.hello.useQuery({text:"teste"});

    const [email, setEmail] = useState("");
    const [password, setPassword] = useState("");


    const handleLogin = () => {
        login({ email, password }, {
            onSuccess: () => {
                router.push('/dashboard')
            },
            onError: (err) => {
                alert(err.message);
            }
        })
        // alert(data?.greeting);
    }
    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="flex flex-col">

                <input type="email" onChange={(e) => setEmail(e.target.value)} value={email} />
                <input type="password" onChange={(e) => setPassword(e.target.value)} value={password} />
                <button onClick={handleLogin}>Login</button>
            </div>
        </>
    )
}

export default Login