import { type NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Knowledge</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="hero min-h-screen bg-base-200">
        <div className="hero-content text-center">
          <div className="max-w-md">
            <h1 className="text-5xl font-bold">Knowledge</h1>
            <p className="py-6">{"=)"}</p>
            <button className="btn-primary btn">Bora</button>
          </div>
        </div>
      </div>
    </>
  );
};

export default Home;
